# -*- coding: utf-8 -*-
"""Copia de app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vtn0Q4zIVnodcVzISxISjyWDEIyr-hlA
"""

import streamlit as st
import time
import random

# --- CONFIGURATION (The "Bank Brain") ---
st.set_page_config(page_title="Agentic Credit Demo", page_icon="💳")

# Mock Database of Users (The "KYA" Layer)
USER_PROFILES = {
    "CEO_Demo": {"score": 820, "limit": 50000, "risk_tolerance": "high"},
    "New_User": {"score": 680, "limit": 2000, "risk_tolerance": "medium"}
}

# --- THE RISK ENGINE (Your "Secret Sauce") ---
def analyze_risk(item_text, price):
    """Simulates the sophisticated risk check your bank performs."""

    # 1. Detect Asset Class
    item_lower = item_text.lower()
    if any(x in item_lower for x in ["flight", "hotel", "business", "laptop", "course"]):
        asset_class = "Productive/Safe"
        risk_multiplier = 0.8  # Lower risk
    elif any(x in item_lower for x in ["crypto", "casino", "gaming", "party"]):
        asset_class = "Volatile/High Risk"
        risk_multiplier = 1.5  # Higher risk
    else:
        asset_class = "General Consumption"
        risk_multiplier = 1.0

    # 2. Calculate Decision
    # (In real life, this calls your Core Banking System)
    user = USER_PROFILES["CEO_Demo"]
    adjusted_limit = user["limit"] / risk_multiplier

    approved = price <= adjusted_limit

    return {
        "approved": approved,
        "asset_class": asset_class,
        "apr": "0.0%" if risk_multiplier < 1.0 else "4.9%",
        "max_auth": round(adjusted_limit, 2)
    }

# --- THE USER INTERFACE (The "Agent") ---
st.title("🤖 Shopping Agent")
st.caption("Powered by ZINIA Embedded Lending Protocol")

# Initialize Chat History
if "messages" not in st.session_state:
    st.session_state.messages = []
    # Agent starts the conversation
    st.session_state.messages.append({
        "role": "assistant",
        "content": "Hello! I am your personal shopping assistant. I have your **Delegated Bank Token** loaded. What would you like to buy today?"
    })

# Display Chat History
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.write(message["content"])

# --- THE INTERACTION LOOP ---
if prompt := st.chat_input("Ex: Book a flight to London for $1200"):
    # 1. Show User Message
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.write(prompt)

    # 2. "Thinking" Simulation
    with st.chat_message("assistant"):
        message_placeholder = st.empty()
        message_placeholder.markdown("🔄 *Consulting Bank Risk Engine...*")
        time.sleep(1.5) # Fake latency to feel "real"

        # 3. Extract Price (Simple Heuristic for Demo)
        try:
            # simple extraction of numbers from text
            price = float(''.join(filter(str.isdigit, prompt)))
            if price < 100: price = 1000 # default fallback if no price found
        except:
            price = 1500 # fallback

        # 4. Call the Risk Engine
        decision = analyze_risk(prompt, price)

        # 5. Formulate Response
        if decision["approved"]:
            response_text = f"""
✅ **Transaction Approved** by [Your Bank]

* **Asset Class Detected:** {decision['asset_class']}
* **Financing Offer:** 12 months @ **{decision['apr']} APR**
* **Virtual Card Generated:** `****-****-****-4242` (Single Use)

*I have executed the purchase using your pre-approved credit line.*
"""
        else:
            response_text = f"⚠️ **Transaction Declined**. This exceeds your adjusted limit for {decision['asset_class']} items."

        message_placeholder.markdown(response_text)
        st.session_state.messages.append({"role": "assistant", "content": response_text})
